### PR TITLE
adopt raw-id for interned keys

### PR DESCRIPTION
**Pull request by nikomatsakis**
Per @matklad's suggestion, create a `RawId` type and use it in place of `u32` for interned keys.

### CODE REVIEW

**Comment by matklad** [comment]
LGTM

**Comment by nikomatsakis** [comment]
I added two changes:

- we do not permit `RawId` to be converted to a `u32`, only `usize` -- seems more forward compat?
- adopt `NonZeroU32` internally -- why not?

**Comment by matklad** [comment]
>we do not permit RawId to be converted to a u32, only usize -- seems more forward compat?

Is there a reason why we might want something bigger than `u32` in the future? If not, I'd stick with exposing `u32`: otherwise we might be just pushing unchecked `as` casts to the clients.

**Comment by nikomatsakis** [comment]
I was just debating about the u32 vs usize distinction myself, since I noticed I had forgotten to change the`MAX` constant to `usize`. I mean, I can't foresee a reason to use `usize` apart from the obvious one (lots and lots of data). I'll stick with u32 for now under the YAGNI principle.

**Comment by matklad** [comment]
>(lots and lots of data) 

that would be16GB to store IDs themselves, since they are dense :)

**Comment by nikomatsakis** [comment]
@matklad no, I mean, the point is not the amount of space the *indices* take, but the max number of values *you can intern*. I was imagining someday we might want a feature that uses `NonZeroUsize` instead of `NonZeroU32` as the representation of a `RawId`, for example.

**Comment by nikomatsakis** [comment]
Or maybe I misunderstood your comment...

**Comment by nikomatsakis** [comment]
Regardless, I agree that it's pretty unlikely to be a problem in practice. =)

**Comment by nikomatsakis** [comment]
(Also, I suppose that, *in that unlikely event*, we could have a `#[salsa::usize_interned]` thing or something, rather than a feature.)

**Comment by nikomatsakis** [comment]
OK, reverted =)

**Comment by matklad** [comment]
I mean that, in order to run out of indices u32, we must, at some point, have 2**32 objects interned. That's indeed lots of data: at least 2**32 * size_of::<u32> to store the indices.

**Pull request merged**
