### PR TITLE
Tracked proposal

### PR DESCRIPTION
**Pull request by nikomatsakis**
I sketched out a variation of the entity API that I am calling tracked (this is a hat-tip to Ember's terminology, cc @wycats). It is the mostly the same ideas, but repackaged in a way that I think is more intuitive. This was inspired by writing the previous tutorial and thinking how things could be a bit cleaner.

To read the proposal, check out the "overview" page on the netlify preview. The tutorial and code have not been fully updated to match yet.

cc #305

### CODE REVIEW

**Comment by 8573** [comment]
> To read the proposal, check out the "overview" page on the netlify preview.

...which is [here](https://deploy-preview-308--salsa-rs.netlify.app/overview.html), though it disappeared from the Netlify bot's comment.

**Comment by nikomatsakis** [comment]
OK!  This is looking good.

@bors r+

**Comment by matklad** [comment]
bors=nikomatsakis

I think we use the other one here

**Comment by matklad** [comment]
bors r=nikomatsakis

I think we use the other one here

**Pull request merged**
