### PR TITLE
Release salsa-0.10.0-alpha4

### PR DESCRIPTION
**Pull request by nikomatsakis**
- Introduce requirement for group storage structs (#130)
- Manually implement Default (#131)

Contributors to this release:

- @cormacrelf
- @nikomatsakis

### CODE REVIEW

**Comment by cormacrelf** [comment]
Hm. Docs.rs failed to build. https://docs.rs/crate/salsa/0.10.0-alpha4/builds/139121

**Comment by nikomatsakis** [comment]
It works on stable for me

**Comment by cormacrelf** [comment]
Docs.rs runs nightly, but seems to be failing on uniform paths, which afaik were stable as of 1.32. Possible nightly regression.

**Comment by nikomatsakis** [comment]
So, I've had this problem on nightly, but only on older nightlies. I was however stuck on an older nightly because RLS wasn't building.

**Pull request merged**
