### PR TITLE
Fix Chinese book link

### PR DESCRIPTION
**Pull request by armoha**
cc @zjp-CN 

- Previous link: https://zjp-cn.github.io/salsa
- Fixed link: https://rust-chinese-translation.github.io/salsa-book/

### CODE REVIEW

**Comment by zjp-CN** [comment]
Oh, yes. I moved the Chinese book to separate repo, and forgot to update the link here :) Thanks!

**Review by XFFXFF — APPROVED** [review]
Thanks!  
bors r+

**Comment by XFFXFF** [comment]
@armoha  The CI fails because the error message for the [`compile_fail`](https://github.com/salsa-rs/salsa/blob/master/salsa-2022-tests/tests/compile_fail.rs) test has changed somewhat on rustc 1.64, and our CI always runs `compile_fail' on the latest stable version of rustc.

Could you update to rustc 1.64 stable in your local environment and run `TRYBUILD=overwrite cargo test -p salsa-2022-tests` and push the changes.

**Comment by armoha** [comment]
It seems to be resolved now.

**Pull request merged**
