### PR TITLE
Add miri to CI

### LINKED ISSUE #463: Add miri to CI
See https://github.com/salsa-rs/salsa/pull/450#issuecomment-1803561467

### PR DESCRIPTION
**Pull request by DropDemBits**
Fixes #463

### CODE REVIEW

**Comment by nikomatsakis** [comment]
This is awesome! I see we are getting CI failures though :( 

I don't know enough about miri to know if these are known limitations or what -- I imagine maybe we just want to run this on a subset of our test suite?

**Comment by DropDemBits** [comment]
miri does have support for shimming out to some foreign functions, though not for `pipe2` currently. This is an issue for any tests using the `insta` crate, which eventually ends up calling `pipe2`.

Thankfully, it's isolated to the older version of salsa, as salsa-2022 doesn't use the `insta` crate for tests. It's been a bit but I think that's what I did to test out the placement new changes in miri.

The unfortunate thing is that we'd need to list out every package that we'd want to run miri on, but I think that's an acceptable compromise for now.

**Comment by DropDemBits** [comment]
Just started to run miri locally including the examples, and it found some UB :eyes:

```
test parser::parse_error ... error: Undefined Behavior: trying to retag from <162748> for SharedReadWrite permission at alloc49986[0x0], but that tag does not exist in the borrow stack for this location
   --> /home/pinwheel/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/non_null.rs:397:18
    |
397 |         unsafe { &*self.as_ptr().cast_const() }
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |                  |
    |                  trying to retag from <162748> for SharedReadWrite permission at alloc49986[0x0], but that tag does not exist in the borrow stack for this location
    |                  this error occurs as part of retag at alloc49986[0x0..0x28]
    |
    = help: this indicates a potential bug in the program: it performed an invalid operation, but the Stacked Borrows rules it violated are still experimental
    = help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md for further information
help: <162748> was created by a SharedReadOnly retag at offsets [0x10..0x28]
   --> /home/pinwheel/Projects/salsa/components/salsa-2022/src/ingredient_list.rs:76:28
    |
76  |             let previous = self.list.compare_and_swap(&guard, Some(vec));
    |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: BACKTRACE (of the first span):
    = note: inside `std::ptr::NonNull::<alloc::sync::ArcInner<std::vec::Vec<salsa_2022::IngredientIndex>>>::as_ref::<'_>` at /home/pinwheel/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/non_null.rs:397:18: 397:46
    = note: inside `std::sync::Arc::<std::vec::Vec<salsa_2022::IngredientIndex>>::inner` at /home/pinwheel/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/sync.rs:1744:18: 1744:35
    = note: inside `<std::sync::Arc<std::vec::Vec<salsa_2022::IngredientIndex>> as std::ops::Deref>::deref` at /home/pinwheel/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/sync.rs:2054:10: 2054:22
```

Curious if #462 is related to this?

**Comment by DropDemBits** [comment]
For now, I made it so that miri only runs on the salsa-2022 packages, but since there is preexisting UB it'll still fail.

**Comment by DropDemBits** [comment]
Whoops, turns out locally I had an outdated `Cargo.lock` file with an older `arc-swap`. :sweat_smile:
Though I think we should bump `arc-swap` to 1.6.0 since 1.5.1 and earlier are known to have UB (see https://github.com/vorner/arc-swap/pull/86).

**Comment by DropDemBits** [comment]
Added a commit bumping the `arc-swap` version, though I can split it into a separate PR if need be.

**Comment by nikomatsakis** [comment]
Thanks, and I appreciate your patience a second time! Things got crazy there.

**Pull request merged**
