### PR TITLE
reduce amount of generated code for `DebugWithDb`

### PR DESCRIPTION
**Pull request by vemoo**
Extract common code that was being repeated for each field of each salsa handled struct to `components/salsa-2022/src/debug.rs` module `helper`.

### CODE REVIEW

**Review by huang12zheng — COMMENTED** [review]
This may also be an option(just about clone):
Fallback remove info about Debug,
and add Debug to method
```rs
trait Fallback<Db>
where
    Db: ?Sized,
{
    fn match_data_type<'a, 'b: 'a, T: Clone>(a: &T, db: &'b Db) -> T {
        a.clone()
    }
}

impl<T, Db> Fallback<Db> for T
where
    T: ?Sized,
    Db: ?Sized,
{
}
```

**Review by nikomatsakis — APPROVED** [review]
Nice.

**Comment by nikomatsakis** [comment]
@huang12zheng I didn't quite understand your suggestion-- seems like it has to do with `clone`, not with `debug` generation

**Pull request merged**
