### PR TITLE
run `cargo test -p salsa-2022-tests` in CI

### PR DESCRIPTION
**Pull request by XFFXFF**
* run `cargo test -p salsa-2022-tests` in CI
* check format first

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Does `--all` not run the `salsa-2022-tests` tests?

**Comment by nikomatsakis** [comment]
Oh! We were..not using `--all`. Maybe we should do that instead?

**Comment by XFFXFF** [comment]
> Oh! We were..not using `--all`. Maybe we should do that instead?

Yes! that's better

**Pull request merged**
